# https://ncleguizamon.co/instalar-sonarqube-docker-compose/
version: "3.7"
services:
  sonarqube:
    image: sonarqube:8.9.9-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
    ports:
      - "8080:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonar-postgresql-conf:/var/lib/postgresql
      - sonar-postgresql-data:/var/lib/postgresql/data

volumes:
  sonarqube-data:
  sonarqube-extensions:
  sonar-postgresql-conf:
  sonar-postgresql-data: